classes:
- system.linux.system.repo.ubuntu
- system.salt.master.pkg
  #- system.salt.master.git
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.reclass.storage.system.ceph_mon_cluster
- cluster.ceph_ha.ceph
- cluster.ceph_ha.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/LotharKAtt/ceph-virtual-lab.git"
#    salt_master_environment_revision: master
#    salt_master_environment_repository: "https://github.com/salt-formulas"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: 127.0.0.1
  salt:
    master:
      environment:
        prd:
          formula:
            ceph:
              source: git
              address: 'https://github.com/LotharKAtt/salt-formula-ceph.git'
              revision: master
        dev:
          formula:
            ceph:
              source: git
              address: 'https://github.com/LotharKAtt/salt-formula-ceph.git'
              revision: master
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
  reclass:
    storage:
      node:
        infra_storage_rack01:
          name: osd<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          repeat:
            count: 3
            start: 0
            digits: 1
            params:
              ceph_host_id:
                value: <<count>>
                start: 1
              single_address:
                value: ceph_osd_node<<count>>_address
                start: 1
                digits: 2
                interpolate: true
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
        infra_config:
          expression: <<node_hostname>>__startswith__cfg
          cluster_param:
            infra_config_address:
              value_template: <<node_control_ip>>
            infra_config_deploy_address:
              value_template: <<node_deploy_ip>>
            cluster_domain:
              value_template: <<node_domain>>
        ceph_osd_01:
          expression: <<node_hostname>>__equals__osd0
          cluster_param:
            ceph_osd_node01_address:
              value_template: <<node_control_ip>>
        ceph_osd_02:
          expression: <<node_hostname>>__equals__osd1
          cluster_param:
            ceph_osd_node02_address:
              value_template: <<node_control_ip>>
        ceph_osd_03:
          expression: <<node_hostname>>__equals__osd2
          cluster_param:
            ceph_osd_node03_address:
              value_template: <<node_control_ip>>
        ceph_mon_01:
          expression: <<node_hostname>>__equals__cmn03
          cluster_param:
            ceph_mon_node01_address:
              value_template: <<node_control_ip>>
        ceph_mon_02:
          expression: <<node_hostname>>__equals__cmn02
          cluster_param:
            ceph_mon_node02_address:
              value_template: <<node_control_ip>>
        ceph_mon_03:
          expression: <<node_hostname>>__equals__cmn03
          cluster_param:
            ceph_mon_node03_address:
              value_template: <<node_control_ip>>
        ceph_cfs:
          expression: <<node_hostname>>__startswith__cfs
          node_class:
            value_template:
              - cluster.<<node_cluster>>.ceph.cfs
